Vagrant.configure("2") do |config|

   config.vm.define "kafka" do |kafka|
    kafka.vm.box = "ubuntu/xenial64"
        kafka.vm.network "private_network", ip: "192.168.33.200"
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "forwarded_port", guest: 2181, host: 2181
	config.vm.network "forwarded_port", guest: 9092, host: 9092
	config.vm.network "forwarded_port", guest: 9093, host: 9093
	config.vm.network "forwarded_port", guest: 9094, host: 9094
	config.vm.synced_folder "./", "/vagrant", type: "virtualbox", disabled: false
	
       config.vm.provider "virtualbox" do |vb|
	vb.memory = "4096"
        end

   end

end